
version: "3"
services:
  app:
    build: ./app
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: test