version: "2"
services:
  # APPLICATION
  app:
    build: ./app 
    ports:
      # Host : Container
      - "80:80"
    depends_on:
      - db
    volumes:
      - "C:/Users/llegrand/Documents/DockerProjects/simple_docker_application/app/src/:/var/www/html/"

  # KEYS STORAGE
  keys:
    build: ./keys

  # DATABASE
  db:
    build: ./bdd
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - C:/Users/llegrand/Documents/DockerProjects/simple_docker_application/bdd/volume/:/var/lib/mysql/
    depends_on:
      - keys
    volumes_from:
      - keys