version: "2"
services:
  # Main application (PHP / Apache)
  app:
    build: ./app 
    restart: always
    ports:
      # Host : Container
      - "80:80"
    depends_on:
      - db
    volumes:
      - "C:/Users/llegrand/Documents/DockerProjects/simple_docker_application/app/src/:/var/www/html/"

  # Database (Mysql)
  db:
    build: ./bdd
    restart: always
    environment:
      #Login Password - Database Infos
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - "C:/Users/llegrand/Documents/DockerProjects/simple_docker_application/bdd/volume:/var/lib/mysql"